### ISSUE TITLE
Areas of Code data is not updated since last week

### ISSUE THREAD

**Issue by sanacl** [mozilla/participation-metrics-org#168]
The aoc enriched index is not updated since last week, this is the error we found in the Docker container error output.

```
2018-04-08 01:46:41,446 - grimoire_elk.elk - ERROR - Problem executing study <bound method GitEnrich.enrich_areas_of_code of <grimoire_elk.enriched.git.GitEnrich object at 0x7f2c86f2c240>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 460, in do_studies
    study(enrich_backend, no_incremental)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/enriched/git.py", line 787, in enrich_areas_of_code
    areas_of_code(git_enrich=enrich_backend, in_conn=in_conn, out_conn=out_conn)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/enriched/study_ceres_aoc.py", line 194, in areas_of_code
    ndocs = aoc.analyze()
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/enriched/ceres_base.py", line 93, in analyze
    process_results = self.process(item_block)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/enriched/study_ceres_aoc.py", line 152, in process
    events_df = git_events.eventize(2)
  File "/usr/local/lib/python3.5/dist-packages/cereslib/events/events.py", line 537, in eventize
    self._add_common_fields(df_columns, item)
  File "/usr/local/lib/python3.5/dist-packages/cereslib/events/events.py", line 175, in _add_common_fields
    self._add_general_info(df_columns, item)
  File "/usr/local/lib/python3.5/dist-packages/cereslib/events/events.py", line 95, in _add_general_info
    project_item = self.enrich.get_item_project(item)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/enriched/enrich.py", line 514, in get_item_project
    project = (self.prjs_map[ds_name][repository])
TypeError: 'NoneType' object is not subscriptable

```

How to reproduce:
* version bitergia/mordred:18.04-01
* project's file at https://github.com/bitergia/projects-mozilla

Setup:
```
[git]
raw_index = git_mozilla_180206
enriched_index = git_mozilla_180206_enriched_180404
latest-items = true
studies = [enrich_demography, enrich_areas_of_code]
```

**Comment by sanacl** [comment]
Solved with the latest release 18.04-01-a.

We are done  here.
